baseURL = 'https://blog.ujunglangit.id/'
languageCode = 'en-us'
title = 'Sepotong ilmu dari UjungLangit'
theme = 'hugo-theme-monochrome'

[params]
  author = "M Azwar Nurrosat"
  description = "A blog about all technical stuff."  
  navbar_title = "Sharing is caring"
  footer = "Copyright © 2023 by Azwar"
  color_scheme = "dark"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ChristopherJHart"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/_ChrisJHart"

  [params.syntax_highlight]
    lib = "prism.js" # "builtin" | "prism.js" (default: "builtin")
  [params.syntax_highlight.prism]
    enable_code_copy = true # default: true
    enable_line_no = true # default: true