[[navbar]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1
[[navbar]]
  identifier = "devops"
  name = "Devops Tutorials"
  url = "/devops/"
  weight = 2  
[[navbar]]
  identifier = "dev"
  name = "Web Dev Tutorials"
  url = "/dev/"
  weight = 3  
[[navbar]]
  identifier = "misc"
  name = "Misc Tutorials"
  url = "/misc/"
  weight = 4    
[[navbar]]
  identifier = "learning"
  name = "Learning Material"
  url = "/learning/"
  weight = 5
  [[navbar]]
    identifier = "svelte"
    name = "Svelte"
    url = "/learning/svelte"
    weight = 1  
    parent = "learning"
  [[navbar]]
    identifier = "sveltekit"
    name = "Svelte Kit"
    url = "/learning/sveltekit"
    weight = 2  
    parent = "learning"
  [[navbar]]
    identifier = "hugo"
    name = "Hugo Blogging"
    url = "/learning/hugo"
    weight = 3  
    parent = "learning"  
[[navbar]]
  identifier = "others"
  name = "Other Blog Post"
  url = "/others/"
  weight = 6
